export const AUTH_CHANGE_NAME_TEXT = "AUTH_CHANGE_NAME_TEXT";
export const AUTH_CHANGE_SURNAME_TEXT = "AUTH_CHANGE_SURNAME_TEXT";
export const AUTH_CHANGE_EMAIL_TEXT = "AUTH_CHANGE_EMAIL_TEXT";
export const AUTH_CHANGE_PASSWORD_TEXT = "AUTH_CHANGE_PASSWORD_TEXT";
export const AUTH_SET_IS_AUTH_VALUE = "AUTH_SET_IS_AUTH_VALUE";
export const AUTH_SET_IS_LOGED_IN = "AUTH_SET_IS_LOGED_IN";

export const VOICE_ASSISTANT_NAME = "VOICE_ASSISTANT_NAME";
export const VOICE_ASSISTANT_GENDER = "VOICE_ASSISTANT_GENDER";
export const VOICE_ASSISTANT_THEME = "VOICE_ASSISTANT_THEME";

export const REGISTRATION_STEPS = "REGISTRATION_STEPS";
export const REGISTRATION_STEP = "REGISTRATION_STEP";
export const REGISTRATION_DONE = "REGISTRATION_DONE";
